M48
; DRILL file KiCad 10.0.3 date 2026-07-08T22:23:12
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-08T22:23:12-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
%
G90
G05
T1
X82.931Y-85.065
X82.931Y-96.495
X86.106Y-90.78
T2
X105.503Y-91.258
X105.503Y-98.258
M30
